# Generated by Django 3.2.7 on 2021-09-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_avg_per', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='市場平均PER')),
                ('m_cur_growth', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='今期営業増益率')),
                ('m_next_growth', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='来期営業増益率')),
                ('m_ratio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='東証１部平均PEG')),
                ('p_avg_per', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='マザーズ単純平均PER')),
                ('p_cur_growth', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='今期営業増益率')),
                ('p_next_growth', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='来期営業増益率')),
                ('p_ratio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='新興PEG')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
        ),
    ]
