# Generated by Django 3.2.7 on 2021-09-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20210923_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='a_sales_comment_next',
            field=models.IntegerField(default=-1, verbose_name='A-来期稼ぐ力'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='a_sales_comment_now',
            field=models.IntegerField(default=-1, verbose_name='A-今期稼ぐ力'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='b_sales_comment_next',
            field=models.IntegerField(default=-1, verbose_name='B-来期稼ぐ力'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='b_sales_comment_now',
            field=models.IntegerField(default=-1, verbose_name='B-今期稼ぐ力'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='c_sales_comment_next',
            field=models.IntegerField(default=-1, verbose_name='C-来期稼ぐ力'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='c_sales_comment_now',
            field=models.IntegerField(default=-1, verbose_name='C-今期稼ぐ力'),
        ),
    ]
